### ISSUE TITLE
Fork request: AtomLinter/linter-shellcheck

### ISSUE THREAD

**Issue by ottok** [pulsar-cooperative/.github#2]
Hi!

The package https://web.pulsar-edit.dev/packages/linter-shellcheck has 137k+ downloads and 280 stars at https://github.com/AtomLinter/linter-shellcheck.

As it is under the AtomLinter org, it has been frozen, and I hereby request it to be forked to the Pulsar Cooperative org following principles outlined at https://github.com/pulsar-cooperative/.github/blob/72a5697835ab1997c10a91c1abba7add1b3ff771/README.md and https://github.com/pulsar-cooperative/.github/blob/72a5697835ab1997c10a91c1abba7add1b3ff771/guides/fork-new-package.md.

I would personally want to fix the bug https://github.com/AtomLinter/linter-shellcheck/issues/150 but since there is no active 'upstream', contributing is hard, and having this package have a new home at the Pulsar Cooperative would enable effective cooperation for the plugin.

Following the [new package doc](https://github.com/pulsar-cooperative/.github/blob/72a5697835ab1997c10a91c1abba7add1b3ff771/guides/setup-new-package.md) above, the new name should probably be 'linter-shellcheck-pulsar'.

I also use [a bunch of other linters](https://optimizedbyotto.com/post/pulsar-best-text-file-and-code-editor/#my-pulsar-config-and-packages) from AtomLinter and might request forking them in the future too.

**Comment by confused-Techie** [comment]
Thanks a ton for contributing here!

Glad to see the request, and I'm totally on board myself.

As this is now the first community requested fork for this repo, I'm talking with some of the other admins to see if we want to have some sort of poll/vote for forking new packages that meet our requirements, or if it'll be handled more as a do-ocracy.

So I'll get back to you as soon as possible with details!

**Comment by confused-Techie** [comment]
The repo is now live and forked! [`pulsar-cooperative/linter-shellcheck-pulsar`](https://github.com/pulsar-cooperative/linter-shellcheck-pulsar).

One thing to keep in mind, I've purposefully not published this package yet to the Pulsar Package Registry, as the package is broken, and has failed all tests, and doesn't seem able to startup properly. So it seems the package is broken, and we wouldn't want to publish a known-bad package, until that is fixed.

So thanks again for contributing, and I hope to see the community step in soon to contribute to this new addition!

**Comment by confused-Techie** [comment]
Actually an update here, via [`pulsar-cooperative/linter-shellcheck-pulsar#3`](https://github.com/pulsar-cooperative/linter-shellcheck-pulsar/pull/3) I've fixed the testing errors, and seems the errors stemmed from two things:

* The package getting important config values using the old package name, which has now been rebranded
* The package expected exact string returns from `shellcheck` which have changed in some versions.

Those issues have been addressed, all tests are passing, and the package is now successfully [published](https://web.pulsar-edit.dev/packages/linter-shellcheck-pulsar)!

**Comment by ottok** [comment]
Thanks!

I switched to using the fork now, did basic testing and seems everything works. The old plugin had 137k downloads. Let's see how this one will gain popularity over time :)

![image](https://github.com/pulsar-cooperative/.github/assets/668724/9a9b83ac-a535-4466-9ee2-8a2614bf080f)

**Comment by ottok** [comment]
I also filed https://github.com/koalaman/shellcheck/pull/2892 to get "upstream" to link to this new plugin instead of the archived old one.

Forking this linter-spellcheck was a good test of how the forking process works. Anyone wanting to repeat this could just look what you in https://github.com/pulsar-cooperative/linter-shellcheck-pulsar/commits/master/ - however in practice it is now a bit difficult to read 13 commits that edited 3 files...

The guide https://github.com/pulsar-cooperative/.github/blob/main/CONTRIBUTING.md is very strict about commits:
> While you develop the package and work on bug fixes, please ensure that you use [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/) in your commit messages. This is how new versions of the package's are released and updated. Failing to follow conventional commits within your PR may mean it will be closed without being merged.

Just as constructive feedback I feel I need to point out that you failed to follow this yourself. You should have had one single commit titled 'feat!: Rebrand plugin after forking to Pulsar Cooperative' in one single Pull Request and polish it until it passes the CI. Such a commit is [atomic](https://optimizedbyotto.com/post/good-git-commit/), follows the Conventional Commits, and is what you want contributors to submit to you as well, right?

Build a healthy community by setting good examples in your work and leading with examples.

**Comment by ottok** [comment]
Shellcheck just merged https://github.com/koalaman/shellcheck/pull/2892 :)
